// Installs, configures and drives a single Prowler App docker compose stack.
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { run } from './exec.js';

const REPO = 'prowler-cloud/prowler';

export async function latestRelease() {
  const res = await fetch(`https://api.github.com/repos/${REPO}/releases/latest`, {
    headers: { Accept: 'application/vnd.github+json', 'User-Agent': 'prowler-manage' },
  });
  if (!res.ok) throw new Error(`GitHub latest release lookup failed: ${res.status} ${res.statusText}`);
  return (await res.json()).tag_name;
}

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': 'prowler-manage' } });
  if (!res.ok) throw new Error(`Download failed: ${url} (${res.status})`);
  return res.text();
}

export function projectName(inst) {
  return `prowler-${inst.slug}`;
}

export function generateSecrets() {
  return {
    authSecret: crypto.randomBytes(32).toString('base64'),
    encryptionKey: crypto.randomBytes(32).toString('base64'),
    postgresAdminPassword: crypto.randomBytes(24).toString('hex'),
    postgresPassword: crypto.randomBytes(24).toString('hex'),
    neo4jPassword: crypto.randomBytes(24).toString('hex'),
  };
}

export function generatePassword() {
  // Prowler requires >= 12 chars; include every character class to satisfy validators.
  const pick = (set, n) => Array.from(crypto.randomBytes(n), (b) => set[b % set.length]).join('');
  const chars = pick('ABCDEFGHJKLMNPQRSTUVWXYZ', 4) + pick('abcdefghijkmnpqrstuvwxyz', 6) + pick('23456789', 4) + pick('!@#%^*-_+', 2);
  return chars.split('').sort(() => crypto.randomInt(3) - 1).join('');
}

function setEnv(text, key, value) {
  const line = `${key}=${/[\s#"'$]|^$/.test(String(value)) || /[+/=]/.test(String(value)) ? `"${value}"` : value}`;
  const re = new RegExp(`^${key}=.*$`, 'm');
  return re.test(text) ? text.replace(re, () => line) : `${text.trimEnd()}\n${line}\n`;
}

export function publicUrl(inst) {
  return inst.hostname ? `https://${inst.hostname}` : `http://localhost:${inst.uiPort}`;
}

function buildEnv(upstream, inst, settings) {
  const s = inst.secrets;
  const values = {
    PROWLER_UI_VERSION: inst.version,
    PROWLER_API_VERSION: inst.version,
    PROWLER_MCP_VERSION: inst.version,
    NEXT_PUBLIC_PROWLER_RELEASE_VERSION: `v${inst.version}`,
    AUTH_URL: publicUrl(inst),
    AUTH_TRUST_HOST: 'true',
    AUTH_SECRET: s.authSecret,
    POSTGRES_ADMIN_PASSWORD: s.postgresAdminPassword,
    POSTGRES_PASSWORD: s.postgresPassword,
    NEO4J_PASSWORD: s.neo4jPassword,
    NEO4J_SERVER_MEMORY_PAGECACHE_SIZE: settings.neo4jMemory,
    NEO4J_SERVER_MEMORY_HEAP_INITIAL__SIZE: settings.neo4jMemory,
    NEO4J_SERVER_MEMORY_HEAP_MAX__SIZE: settings.neo4jMemory,
    DJANGO_SECRETS_ENCRYPTION_KEY: s.encryptionKey,
    DJANGO_ALLOWED_HOSTS: 'localhost,127.0.0.1,prowler-api',
    CODE_REVIEW_ENABLED: 'false',
  };
  let text = `# Generated by prowler-manage for instance "${inst.name}" (${inst.tenantDomain})\n${upstream}`;
  for (const [k, v] of Object.entries(values)) text = setEnv(text, k, v);
  return text;
}

// Bind UI and API to loopback on per-instance ports and drop host ports for internal services,
// so many stacks can run side by side. cloudflared reaches the UI on 127.0.0.1.
// First-time database init on Docker Desktop bind mounts is slow, so the upstream
// healthchecks (none or a short start_period) get a grace period. The API runs all Django
// migrations before /health/live answers; worker and worker-beat wait on it being healthy.
function buildOverride(inst) {
  return `# Generated by prowler-manage. Do not edit; changes are overwritten.
services:
  api:
    ports: !override
      - "127.0.0.1:${inst.apiPort}:8080"
    healthcheck:
      start_period: 600s
      start_interval: 5s
  ui:
    ports: !override
      - "127.0.0.1:${inst.uiPort}:3000"
  postgres:
    ports: !reset []
    healthcheck:
      start_period: 180s
      start_interval: 5s
  valkey:
    ports: !reset []
  neo4j:
    ports: !reset []
    healthcheck:
      start_period: 300s
      start_interval: 5s
  mcp-server:
    ports: !reset []
`;
}

/** Download the compose file and .env of a Prowler release and write this instance's config. */
export async function writeStack(inst, settings, log) {
  // The instance folder holds .env with database passwords and keys: owner-only (Docker runs as root
  // and still reads it; containers see only their own bind mounts).
  fs.mkdirSync(inst.dir, { recursive: true, mode: 0o700 });
  const raw = `https://raw.githubusercontent.com/${REPO}/${inst.version}`;
  log(`Downloading Prowler ${inst.version} compose files`);
  const compose = await fetchText(`${raw}/docker-compose.yml`);
  const env = await fetchText(`${raw}/.env`);
  fs.writeFileSync(path.join(inst.dir, 'docker-compose.yml'), compose);
  fs.writeFileSync(path.join(inst.dir, '.env.upstream'), env);
  writeSecretFile(path.join(inst.dir, '.env'), buildEnv(env, inst, settings));
  fs.writeFileSync(path.join(inst.dir, 'docker-compose.override.yml'), buildOverride(inst));
}

function writeSecretFile(file, text) {
  fs.writeFileSync(file, text, { mode: 0o600 });
  fs.chmodSync(file, 0o600);
}

/** Rewrite .env/override from the cached upstream files (after an edit, no download). */
export function rewriteConfig(inst, settings) {
  const env = fs.readFileSync(path.join(inst.dir, '.env.upstream'), 'utf8');
  writeSecretFile(path.join(inst.dir, '.env'), buildEnv(env, inst, settings));
  fs.writeFileSync(path.join(inst.dir, 'docker-compose.override.yml'), buildOverride(inst));
}

export function compose(inst, args, log) {
  return run('docker', ['compose', '-p', projectName(inst), ...args], { cwd: inst.dir, log });
}

/** Map of compose project name → status string ("running(9)", "exited(9)", ...). */
export async function composeStatuses() {
  try {
    const { stdout } = await run('docker', ['compose', 'ls', '-a', '--format', 'json']);
    return Object.fromEntries(JSON.parse(stdout || '[]').map((p) => [p.Name, p.Status]));
  } catch {
    return null; // docker unavailable
  }
}

async function waitFor(url, label, timeoutMs, log) {
  const deadline = Date.now() + timeoutMs;
  log(`Waiting for ${label} (${url})`);
  let last = 0;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(5000) });
      if (res.ok) return log(`${label} is up`);
    } catch {}
    if (Date.now() - last > 30000) {
      log(`...still waiting for ${label}`);
      last = Date.now();
    }
    await new Promise((r) => setTimeout(r, 3000));
  }
  throw new Error(`${label} did not become healthy within ${Math.round(timeoutMs / 60000)} min`);
}

export async function isApiUp(inst) {
  try {
    return (await fetch(`http://127.0.0.1:${inst.apiPort}/health/live`, { signal: AbortSignal.timeout(5000) })).ok;
  } catch {
    return false;
  }
}

export function waitApi(inst, log) {
  return waitFor(`http://127.0.0.1:${inst.apiPort}/health/live`, 'Prowler API', 15 * 60000, log);
}

export async function waitHealthy(inst, log) {
  await waitApi(inst, log);
  await waitFor(`http://127.0.0.1:${inst.uiPort}/api/health`, 'Prowler UI', 10 * 60000, log);
}

// ---------- Prowler REST API (JSON:API) ----------

class ProwlerApi {
  constructor(inst) {
    this.base = `http://127.0.0.1:${inst.apiPort}/api/v1`;
    this.token = null;
  }

  async call(method, apiPath, body) {
    const res = await fetch(`${this.base}${apiPath}`, {
      method,
      headers: {
        'Content-Type': 'application/vnd.api+json',
        Accept: 'application/vnd.api+json',
        ...(this.token ? { Authorization: `Bearer ${this.token}` } : {}),
      },
      body: body ? JSON.stringify(body) : undefined,
    });
    const text = await res.text();
    const json = text ? JSON.parse(text) : {};
    if (!res.ok) {
      const detail = (json.errors || []).map((e) => e.detail || JSON.stringify(e)).join('; ') || res.statusText;
      const err = new Error(`Prowler API ${method} ${apiPath} → ${res.status}: ${detail}`);
      err.status = res.status;
      throw err;
    }
    return json;
  }

  async login(email, password) {
    const r = await this.call('POST', '/tokens', { data: { type: 'tokens', attributes: { email, password } } });
    this.token = r.data.attributes.access;
  }
}

function m365Secret(creds) {
  const secret = { tenant_id: creds.tenantId, client_id: creds.clientId };
  if (creds.clientSecret) secret.client_secret = creds.clientSecret;
  if (creds.certificateContent) secret.certificate_content = creds.certificateContent;
  return secret;
}

/**
 * Idempotently bring a fresh stack to a usable state: admin account, M365 provider,
 * credentials, connection test and daily scan schedule. Progress is saved on `inst.init`
 * so a failed run can be resumed with "Launch".
 */
export async function initialize(inst, creds, save, log) {
  const api = new ProwlerApi(inst);
  const init = { ...(inst.init || {}) };
  const commit = () => save({ init: { ...init } });

  try {
    await api.login(inst.adminEmail, inst.adminPassword);
    log(`Logged in as ${inst.adminEmail}`);
  } catch {
    log(`Creating Prowler admin user ${inst.adminEmail}`);
    await api.call('POST', '/users', {
      data: {
        type: 'users',
        attributes: { name: 'Administrator', email: inst.adminEmail, password: inst.adminPassword, company_name: inst.name },
      },
    });
    await api.login(inst.adminEmail, inst.adminPassword);
  }
  init.user = true;
  commit();

  if (!init.providerId) {
    const existing = await api.call('GET', `/providers?filter[provider]=m365&filter[uid]=${encodeURIComponent(inst.tenantDomain)}`);
    if (existing.data?.length) {
      init.providerId = existing.data[0].id;
    } else {
      log(`Registering Microsoft 365 tenant ${inst.tenantDomain}`);
      const r = await api.call('POST', '/providers', {
        data: { type: 'providers', attributes: { provider: 'm365', uid: inst.tenantDomain, alias: inst.name } },
      });
      init.providerId = r.data.id;
    }
    commit();
  }

  if (!init.secretId) {
    if (!creds?.clientSecret && !creds?.certificateContent) {
      throw new Error('M365 client secret is required to finish initialization; use Edit to supply it');
    }
    log('Storing M365 app credentials in Prowler');
    const r = await api.call('POST', '/providers/secrets', {
      data: {
        type: 'provider-secrets',
        attributes: { secret_type: 'static', name: `${inst.name} app registration`, secret: m365Secret(creds) },
        relationships: { provider: { data: { type: 'providers', id: init.providerId } } },
      },
    });
    init.secretId = r.data.id;
    commit();
  }

  await testConnection(api, init.providerId, log);

  if (!init.schedule) {
    try {
      await api.call('POST', '/schedules/daily', {
        data: { type: 'daily-schedules', attributes: { provider_id: init.providerId } },
      });
      log('Daily scan scheduled (first scan starts now)');
    } catch (e) {
      log(`WARNING: could not schedule daily scan: ${e.message}`);
    }
    init.schedule = true;
    commit();
  }
  init.done = true;
  commit();
}

async function testConnection(api, providerId, log) {
  try {
    await api.call('POST', `/providers/${providerId}/connection`);
    log('Connection test queued; result appears on the provider in Prowler UI');
  } catch (e) {
    log(`WARNING: connection test could not be started: ${e.message}`);
  }
}

export async function updateCredentials(inst, creds, log) {
  const api = new ProwlerApi(inst);
  await api.login(inst.adminEmail, inst.adminPassword);
  const { providerId, secretId } = inst.init || {};
  if (!providerId || !secretId) throw new Error('Instance is not initialized yet; use Launch to finish setup');
  log('Updating M365 app credentials in Prowler');
  await api.call('PATCH', `/providers/secrets/${secretId}`, {
    data: { type: 'provider-secrets', id: secretId, attributes: { secret_type: 'static', secret: m365Secret(creds) } },
  });
  await api.call('PATCH', `/providers/${providerId}`, {
    data: { type: 'providers', id: providerId, attributes: { alias: inst.name } },
  }).catch((e) => log(`WARNING: could not rename provider: ${e.message}`));
  await testConnection(api, providerId, log);
  // Instances on a client secret use the same secret for their Azure subscriptions.
  if (inst.authMethod === 'secret' && creds.clientSecret && inst.azure?.subscriptions?.length) {
    await updateAzureSecrets(inst, creds, log, api);
  }
}

const azureSecret = (creds) => ({ tenant_id: creds.tenantId, client_id: creds.clientId, client_secret: creds.clientSecret });

/**
 * Register Azure subscriptions as providers (uid = subscription ID) with the app's credentials, test
 * them and schedule daily scans. Idempotent; `known` holds the records of an earlier run.
 */
export async function connectAzure(inst, subs, creds, known, log) {
  const api = new ProwlerApi(inst);
  await api.login(inst.adminEmail, inst.adminPassword);
  const records = [];
  for (const sub of subs) {
    const rec = { id: sub.id, name: sub.name, ...known.find((k) => k.id === sub.id) };
    const alias = `${inst.name} · ${sub.name}`;
    if (!rec.providerId) {
      const existing = await api.call('GET', `/providers?filter[provider]=azure&filter[uid]=${sub.id}`);
      rec.providerId = existing.data?.[0]?.id
        || (await api.call('POST', '/providers', { data: { type: 'providers', attributes: { provider: 'azure', uid: sub.id, alias } } })).data.id;
      log(`Prowler: registered Azure subscription ${sub.name}`);
    }
    if (!rec.secretId) {
      const provider = await api.call('GET', `/providers/${rec.providerId}`);
      rec.secretId = provider.data?.relationships?.secret?.data?.id || null;
    }
    if (rec.secretId) {
      await api.call('PATCH', `/providers/secrets/${rec.secretId}`, {
        data: { type: 'provider-secrets', id: rec.secretId, attributes: { secret_type: 'static', secret: azureSecret(creds) } },
      });
    } else {
      rec.secretId = (await api.call('POST', '/providers/secrets', {
        data: {
          type: 'provider-secrets',
          attributes: { secret_type: 'static', name: `${inst.name} Azure`, secret: azureSecret(creds) },
          relationships: { provider: { data: { type: 'providers', id: rec.providerId } } },
        },
      })).data.id;
    }
    await testConnection(api, rec.providerId, log);
    if (!rec.schedule) {
      try {
        await api.call('POST', '/schedules/daily', { data: { type: 'daily-schedules', attributes: { provider_id: rec.providerId } } });
        log(`Prowler: daily scan scheduled for ${sub.name} (first scan starts now)`);
      } catch (e) {
        log(`WARNING: could not schedule daily scan for ${sub.name}: ${e.message}`);
      }
      rec.schedule = true;
    }
    records.push(rec);
  }
  return records;
}

/** Switch every Azure provider of the instance to new credentials (secret renewal). */
export async function updateAzureSecrets(inst, creds, log, api) {
  if (!api) {
    api = new ProwlerApi(inst);
    await api.login(inst.adminEmail, inst.adminPassword);
  }
  for (const rec of inst.azure?.subscriptions || []) {
    if (!rec.secretId) continue;
    await api.call('PATCH', `/providers/secrets/${rec.secretId}`, {
      data: { type: 'provider-secrets', id: rec.secretId, attributes: { secret_type: 'static', secret: azureSecret(creds) } },
    });
  }
  log(`Updated the Azure client secret in Prowler for ${inst.azure.subscriptions.length} subscription(s)`);
}

/**
 * Delete an instance folder. On Linux the database/cache/graph data under _data/ is owned by the
 * container users (postgres, valkey, neo4j, uid 1000 for the API), so a non-root manager can't
 * delete it directly; a throwaway container removes it instead.
 */
export async function removeInstanceDir(dir, log) {
  try {
    fs.rmSync(dir, { recursive: true, force: true });
    return;
  } catch (e) {
    if (!['EACCES', 'EPERM', 'ENOTEMPTY'].includes(e.code)) throw e;
  }
  log('Removing container-owned data files with a helper container');
  await run('docker', ['run', '--rm', '-v', `${path.resolve(dir)}:/instance`, 'busybox:1.37.0', 'sh', '-c', 'rm -rf /instance/_data /instance/* /instance/.[!.]*'], { log });
  fs.rmSync(dir, { recursive: true, force: true });
}

/**
 * Check the Docker engine and Compose plugin. The generated override file uses `!reset`/`!override`
 * tags, which need Compose 2.24.4 or later (older distro packages ship 2.20 and earlier).
 */
export async function dockerCheck() {
  const out = { docker: null, compose: null, ok: false, problems: [] };
  try {
    out.docker = (await run('docker', ['version', '--format', '{{.Server.Version}}'])).stdout.trim();
  } catch (e) {
    out.problems.push(`Docker engine not reachable (${e.message.split('\n')[0]}). ${process.platform === 'linux' ? 'Is the service running, and is this user in the docker group?' : 'Is Docker Desktop running?'}`);
  }
  try {
    out.compose = (await run('docker', ['compose', 'version', '--short'])).stdout.trim().replace(/^v/, '');
    const [a, b, c] = out.compose.split(/[.-]/).map(Number);
    const tooOld = a < 2 || (a === 2 && (b < 24 || (b === 24 && c < 4)));
    if (tooOld) out.problems.push(`Docker Compose ${out.compose} is too old; 2.24.4 or later is required (install docker-compose-plugin from Docker's repository)`);
  } catch {
    out.problems.push('Docker Compose plugin not found ("docker compose"); install docker-compose-plugin');
  }
  out.ok = out.problems.length === 0;
  return out;
}
